workflows:
  default-workflow:
    name: Default Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "BMI Calculator.xcworkspace" # <-- Put the name of your workspace here.
        XCODE_SCHEME: "BMI Calculator" # <-- Put the name of your scheme here.
        BUNDLE_ID: "com.souvik-biswas.BMI-Calculator" # <-- Put your Bundle Id here.
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmhIR1hjb2VuZlNUZ09VUHdONnBpUzdiZnFYal9ydlpPVzV5cWQ5MEtRUlFIYnlFUjd0eEZIWUpPamxxMTNERFU4WVB1alRnTHZscmtLYTUtRVE2RTZYY1gyS0E1WFR4M0FMWWYyeHltWW82SDh3c2NwNWtLZVZ6SEhucEJnVjcwMF84YnQ=) # <-- Put your encrypted App Store Connect Issuer Id here
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmhIR1lfOTZ4TW03QVlsSWtCZmRMWVFRczA2ZUNwVzgzdTRkRTkydnRkMDhKRV8ySTJORWEyZUpzWV9PUHlLcGROWVN0aGRUVXR5dU9jdlozb1NrZDFLR09XdlE9PQ==) # <-- Put your encrypted App Store Connect Key Identifier here
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhIR2FpM0lFOWJJVVVkLWhXZWFiRm45T0VQcWg5Tk5ieDZJUTBSWDlOeGpNWGtCRlc5bnp0UHFmdkdFVTNMYW9zNWM1WkN1M01vajM5S04ySDhxOHZobjVIVFljTndZdTk3dFBmUmhJWExMTW1vSFR4NXJZVjc5VXdVRFpVSDBsd1hSdkl2YmM1aVoyTFJ1WE5fZzhKdFl6ekoxM0ZKUnkwbFVlRGNrQ2ZiUmFiMnNKRHRabHlsWWdYenFXckNIRjlTZmkzQ2JmZkhnZk5TQ1dUN1AzY0JTdWtVMFlmQVpEdjNGQW9RSUFFMWxDUzRmb3RmSUNXaWt0d0ZCUnB6aUtsUFBGU1AwcmJUeEUyZFpYQzBNb05iU3ZhR09wa19MZXl6VFpLSlRpRkNtaW5UQWM2UnpLeUx2TWRTdzliZl9LSzR0X2M4clBlRmdsaHRFNXpHenZWSXI4RUk2VUdhamE2a0FYaUM0UnplX3lzUEpTRjUwQXoyUGpTNTR1VENmcTV5d2hkMmtRRFBiS3J4cEhjNlVsT0ZPV2xyZ3dma2RjUW1HRDZBTTRJdmFBVjVFaz0=) # <-- Put your encrypted App Store Connect Private Key here
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhIR2RMVTFCWi16cTg3SzJCTEdSalA5MGMxNWZNdUVrUkxlVWhSRzJ1T1VqN1VYenBKZll1ZU9za1F5Yk9OQWxxLXo0elhmcWlwbE9Uc1FfSlZHZWU3RzFQLUFxd0hBbU5mWDlFbXBqOHlObmFTTlEyWlh0TU84d193SS1WUFlmZzlMZjNqckZyWTVKT1lLQVl0cl9rTkNCV3ZxUW94ZS1YVzdNb0hMOTBhWTlEUlpPVmQ5VE9fdVM4ZllUQ2hhWGZhelBLZmYyNHEzc0o1c0pHYlo2QTk1cl9zaC1QZGxiUENGeWJLbU9TVjJUYXpXcHg2d2FOV2txZ2hsMVdtdVJmcG9zVUpSMHhFMTZDMTZCUW9ibmg2ZEtXdU1nbGZ6Y1lETXlsSlZ0MkdwWXhpTGo5X1htczA5VjdxX2dKRGJkX0Q0QTN4eVIydWVlOXhuWFhhU0NrSmlCRHE2SWN0QnlzVjB1d1ZIS3pQVjBWR2xjcFZwcTIxa3RTV1gtR21FY1VWaGhJSkFBVVFWakpJbVowN1RwbG9KQzJxQkp5Rl9oMkJaa3d3cnZoZ2pOZGFhbjhtYXdua1ZjSWxOS2I5NzNxRFpDMU9feGVTeFJWZTJpTXZLN3RSQTduQmpwakVScFJvbkpta3VpaE9VT3ZQWFNkRElpV3c2NjlXeVRNX1pmalJlS0pwdTN6Z29vTm01UW11M1ItMUhsWHYtdmN6LWx4VjNmanZNSVRsR0tyUF9hMDhycExfeS1OZ1NIdlkwdzVrSFlZamR2bW5abHNzcThZcFNuQTM5cG5KM3JURXhJR1gycE5mUXBPU2hqYlMtamhEOXM3RXRoT1hkWk9FRkVuc0ozcDNqdFRFdUthZm85TWRBMGF5VE5QSjdDM0tVWVNVY0h0TTIwTW81ck5Qb2k3dnVFclhFMUVRdVoxVk5Pck13WHdlNEJyS1VFa2h3aXU2d0dWSWtTNmItclJjWGZGQlk3SF9jMEhXdjBsMER4enBuNmt2VWh3RG1KelpwUDNPWUNwcW5WTEtmLXp5OHFBQnBrMUk0RHdZUmxKUGN4aUhiZW5SeXRIaTZBSzBEc3dDNldjMDhnT0dHRWRhSkxTSHJ2dWtwcEVfS0swd1JIV3FydFhEcVZQOWM5T1hsN1JRQVRWWldLQnRSZ0prYTExaDZCX183Um9ibnRrUGZQY2wwZmVObXVBdGZTMnVHbWR5ZGpXcFVlUzdSUFFGSmZHVUhoTTJGVVIxU2RXZEZlUjNhVWpEOGxiMnpxazNYQkdyXzM3bjNhbll5SGg2bFdQMUM4a2d0Ylhrb3U3UTd6N1IwQU15cFZqeWJtbDZPSmpHVVdtdnRuVzd4SXE3VXR4WVEzSFdNWmpaTDFtYkxZV3JuQ2hWMDhGUUJPd2JNLTB0WTBhZjktUXY2Wk9XVlhhcnVZbHdoeW9QVFJmaEdmajFVNW1CSUxVNVgzUktfX1lmY1ZzZ05VZzE2OHFKdHdJLUtSVFViQm02NC1ZS3F1TDR1aFZpT3VUYjliZkU4OUtQT2VjUXE5b1ZpUnBJRDBjNkpNVmJBX1dHdUpTTnNfV0dQaDA5RUZWM0RyRmhpMVA4NUNrbVNkbG0xSTVFbkEySUJyMi1QWDY2QllXOWNUMDItNHhreXBJRm1na2d2QkRhQ1BUWlJvdFEyUTMxeFJMYXRkUEhRUE1qYm1WMl9aMmRJdDVWWXlpUFhJeDBNeWZIcmduX0FhR3N4dGdEOHREVHJIQm5iQ2hXNnpac2h6RXMwR0tlOTctc2dJbzVDM3U2dllBOW9vYUhQaEJYU2NNZEdlVWdCZ3VZdWpqMUlNNklScnJhdjVaZUx5SG84MHpJZ3E5MWJScktMNE5rZTZQTkRaa0JSN2NmNnUxNVprZTBLaXBVWFJueTZZd0RMWGRwamxxWngyMTAxNVV1UWZxY1ZIVmoybDdJRFF2QkNPeVpmS3dfVXpVa3Q1aHp4UjNtWlpCcTg2dnlOWXBMQVJTME1qMDlhdU9qUlR0d2JjRTFtVzNxalNWUllIcG5BVlN3b2xiNHR0SkU3eGhyZjB1aGRsX2xSc2ViclZjc29LbzBQbGVCZ1BpYWMyaDlHUHRzblZQXzhtRllwRzlxNFdpVDZYMU03SVBoSXZlWHkzZlV4R2oyZVhjemhkZHhCWW9JTGxTZUw3QWw2QjZGWEJqN0hEZnlzUmt0Q0dZQnIxTmdGNDFyQ0lwSlBrRHNHZUFDXzZjeWtrWFpKeU12alpDN25ybE5ieEw2ZENYS2g2VVVVLUVsenRCRGlFb2IxZ2JQRWJyUC1NQ1JxZm5qb3lxN0pSaXFmcXFtYjU3WjRJM1V4b0NVbEV5d2ZVZnZxekY2eTBjOVAtczZYS0dFUFphdE9pT3RITE9QNUlDRDRIcjFuLW52am5lMTk4eWlGVEZ3Wk1pRS00SDgyVkVyd0xEXzBrQWJYTkd2cHpBaU83bDhDckZYMGVaUVdicnNRcjJiRkZocUdzTU5CUkxiUTBSZWdiSF9oZFNQVWkxQURkaDE3em5Ga0EzaHBRbWtWMC1pVUN1M08yWG5yVVJqTU0zWlJOcG14WFNuNHI5dVJMNnhnYUpDRnJnb0JJb3FvbE1ULUNMUm10M2E3WkNLdjBhSGVYbDhndjctek5ZU3V5UlFZdkR2VlRIYVdHaVc4U3lEd3FLQkNJMm94T04zNGJzVVRYV0I5bXRvdDRYZ0NDX3A2c20ybDY4d3hvVnpHTTgtaC0yVnVIbmZWYWFmUVFwSGVEaU9iWkt1dk5NVnhCQzNGZ015cTRrSUExTC1iazJVNnhGempWVnZ2VlhwSmJnU3dVYldIcjJybVJNZ0xGeWtnbDRodDJUQTZ6b0ZzVHNOd3N4ZEd3T3ItUzlqNmpZOUhwczlZblJqVUJzaGxXYjNWY1plS2x6TXlacmdCTk1QeUhQTWszbk94MENFYUtzZGJUaEdtbGdoQnNoZjYteGpJMWxJYXV0bFhUNC1wX0ZYUnpvd28tZ1l5NGdid3l2emRYQ09kZUdObnR2X2l6V0hKLUdRMG9SODBucmpMQWZNemdL) # <-- Put your encrypted Certificate Private Key here
        APPLE_ID_EMAIL: sbis1999@gmail.com # <-- Put your encrypted Apple Id email address here
        APP_SPECIFIC_PASSWORD: Encrypted(Z0FBQUFBQmVZbW5ZSVAxaDJOSVVWaGl5bnhoajdMZU9VNmNBcFFvd0cxZDEweUUxcFBsWVpoTi1xLWczbzJWTkkybURXVlJoY25TVDlUQmRidC1QQ3ZFa0Fkd3RRbGdway1xMk9hTGNGMmx0ZmVvbXR6MG9lQnc9) # <-- Put your encrypted App Specific password address here
        FLUTTER_DIRECTORY: bmi_flutter
        IOS_DIRECTORY: BMI\ Calculator
      flutter: v1.12.13+hotfix.8
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        working_directory: bmi_flutter
        script: |
          flutter packages pub get
          find . -name "Podfile" -execdir pod install \;
      - name: Test Flutter app
        working_directory: bmi_flutter
        script: flutter test
      - name: Build Flutter app
        working_directory: bmi_flutter
        script: flutter build ios --release --no-codesign
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        working_directory: BMI\ Calculator
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_DEVELOPMENT --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Set up code signing
        working_directory: BMI\ Calculator
        script: xcode-project use-profiles
      - name: Increment build number
        working_directory: BMI\ Calculator
        script: |
          #!/bin/sh
          set -e
          set -x
          agvtool new-version -all $(($BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        working_directory: BMI\ Calculator
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com
      app_store_connect:
        apple_id: $APPLE_ID_EMAIL
        password: $APP_SPECIFIC_PASSWORD
      # app_store_connect:
      #   app_id: com.souvik-biswas.BMI-Calculator
      #   apple_id: sbis1999@gmail.com
      #   password: Encrypted(Z0FBQUFBQmVZbW5ZSVAxaDJOSVVWaGl5bnhoajdMZU9VNmNBcFFvd0cxZDEweUUxcFBsWVpoTi1xLWczbzJWTkkybURXVlJoY25TVDlUQmRidC1QQ3ZFa0Fkd3RRbGdway1xMk9hTGNGMmx0ZmVvbXR6MG9lQnc9)
